const GIPHY_API_KEY = process.env.GIPHY_API_KEY;
const GIPHY_SEARCH_BASE_URL = process.env.GIPHY_SEARCH_BASE_URL;
const GIPHY_TRENDING_BASE_URL = process.env.GIPHY_TRENDING_BASE_URL;

const FIXED_IMAGE_WIDTH = '200px';
const APP_NAME = process.env.REACT_APP_NAME || 'Giftopia!';

export { GIPHY_API_KEY, GIPHY_SEARCH_BASE_URL, GIPHY_TRENDING_BASE_URL, FIXED_IMAGE_WIDTH, APP_NAME };
